### ISSUE TITLE
Additional code with pyMC

### ISSUE THREAD

**Issue by SamueleSoraggi** [storopoli/Bayesian-Statistics#119]
Hi everyone, and first of all thanks for this amazing repository.
I wanted to ask if you are thinking about adding python with pyMC as another language for your course, and if eventually you could find a contribution to implement it valuable. Eventually I could help with that part.
Cheers and keep up the great work!

**Comment by storopoli** [comment]
Please check https://github.com/storopoli/Bayesian-Statistics/blob/e981fdc0d5ffba0bc78f60736a01a1cb3d69d389/slides/00-tools.typ#L168-L186

I am not supporting Python here, sorry.

Two arguments:

1. All models are tested in CI.
   To be honest, I don't want to mess with Python deployment. I have too much PTSD.

2. This is a graduate course, hence we expect the target audience to have a critical approach to MCMC Samplers.
   This is VERY easy to do with Julia, it's Julia all the way down, hence the argument in favor of Turing.
   This is a PITA with C++ code. And I don't want the target audience to be experts in Python <-> C++ bindings.

With that stated, IF you want to make a PR that adds all models in PyMC and test them in CI the way they are tested with Turing and Stan, the PR will be merged.
If by any chance CI breaks in the future and I open an issue tagging you, if no reply is received in 1 month the PyMC code will be removed from the repo.

**Comment by SamueleSoraggi** [comment]
Thanks for the answer and I can see now why you go with the other tools! 
I should have checked that intro slide before!
Cheers :)

**Comment by storopoli** [comment]
Also relevant: https://storopoli.io/Bayesian-Julia/pages/01_why_Julia/

In the end Python, in the context of scientific computing, data science, stats, MCMC etc., is just a busboy for C/C++/FORTRAN.
A nice language to do quick and dirty prototype or use as a "glue" language if bash is too ugly for you.
