### ISSUE TITLE
`LKJCholesky` Example 

### ISSUE THREAD

**Issue by joshualeond** [storopoli/Bayesian-Statistics#36]
Hi @storopoli, just wanted to let you know that your original `LKJCholesky` usage that you commented out in `12-hierarchical_varying_intercept_slope-cheese.jl` now works thanks to the `Turing.jl` team: https://github.com/TuringLang/Turing.jl/issues/1870. 

I used the default `NUTS` settings with the `0.65` target acceptance ratio and that had closer results to your Stan example.

**Comment by storopoli** [comment]
Thanks! I was following the issue in `Turing.jl`. Do you mind making a PR?
